version: "3"
services:
  database:
    image: spope5/cracker-db:latest
    container_name: cracker-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    restart: always
    volumes:
      - ./cache/postgres:/var/lib/postgresql/data
  cache:
    image: redis:6.2-alpine
    container_name: cracker-redis
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ./cache/redis:/data
  mongodb:
    image: mongo:4.4.21
    container_name: cracker-mongo
    command: mongod --auth
    ports:
      - "${MONGO_PORT}:27017"
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DB}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - ./cache/mongo:/data/db
      - ./initmongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
