version: "3"
services:
  database:
    image: postgres:alpine
    container_name: pg
    environment:
      # TODO: add secrets to env vars
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      # TODO: add ports to env vars
      - "5432:5432"
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    build:
      dockerfile: Dockerfile
      context: ./database
  cache:
    image: redis:6.2-alpine
    container_name: redis
    restart: always
    ports:
      # TODO: add ports to env vars
      - "6379:6379"
    volumes:
      - ./cache:/data
  # DEV TOOLS ONLY BEYOND THIS POINT
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: spope@blockchains.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5000:80"
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin
