version: "3"
services:
  database:
    image: postgres:alpine
    container_name: pg
    environment:
      # TODO: add secrets to env vars
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      # TODO: add ports to env vars
      - "5432:5432"
    restart: always
    volumes:
      - ./cache/postgres:/var/lib/postgresql/data
    build:
      dockerfile: Dockerfile
      context: ./database
  cache:
    image: redis:6.2-alpine
    container_name: redis
    restart: always
    ports:
      # TODO: add ports to env vars
      - "6379:6379"
    volumes:
      - ./cache/redis:/data
  mongodb:
    image: mongo
    container_name: mongo
    command: mongod --auth
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: mongo
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    volumes:
      - ./cache/mongo:/data/db
      - ./initmongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  # DEV TOOLS ONLY BEYOND THIS POINT
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo
      ME_CONFIG_MONGODB_URL: mongodb://mongo:mongo@mongodb:27017/
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: spope@blockchains.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "4000:80"
    volumes:
      - ./cache/pgadmin:/var/lib/pgadmin
