version: "3"
services:
  database:
    image: spope5/cracker-db:latest
    container_name: pg
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  cache:
    image: redis:6.2-alpine
    container_name: redis
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ./cache:/data
